// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // CLI operations (migrate/seed/studio) need a non-pooled connection for the
  // shadow database; the app itself still connects via DATABASE_URL (pooled)
  // through src/config/prisma.ts.
  datasource: {
    url: process.env["DIRECT_DATABASE_URL"],
  },
});
